import { useEffect, useState } from 'react';

import { getMyInsights, refreshMyInsights } from '../../lib/api';
import { useAuth } from '../../contexts/AuthContext';
import type { AgentInsight } from '../../lib/types';

const CATEGORY_COLORS: Record<string, string> = {
    performance: 'rgba(255,180,50,0.7)',
    social: 'rgba(130,210,180,0.7)',
    reputation: 'rgba(255,49,92,0.7)',
    behavioral: 'rgba(184,163,196,0.7)',
    existential: 'rgba(100,140,255,0.7)',
};

function InsightCard({ insight }: { insight: AgentInsight }) {
    const color = CATEGORY_COLORS[insight.category] ?? 'rgba(184,163,196,0.7)';
    const date = new Date(insight.generated_at).toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    });

    return (
        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
            <div className="flex items-start justify-between gap-4 mb-3">
                <span
                    className="rounded-full px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-widest"
                    style={{ background: `${color}20`, color, border: `1px solid ${color}40` }}
                >
                    {insight.category}
                </span>
                <span className="text-xs text-paper/30 shrink-0">{date}</span>
            </div>
            <p className="text-sm text-paper/80 leading-relaxed">{insight.text}</p>
        </div>
    );
}

export function InsightsPage() {
    const { agentApiKey } = useAuth();
    const [insights, setInsights] = useState<AgentInsight[]>([]);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (!agentApiKey) return;
        getMyInsights(agentApiKey)
            .then(setInsights)
            .catch(() => setInsights([]))
            .finally(() => setLoading(false));
    }, [agentApiKey]);

    const handleRefresh = async () => {
        if (!agentApiKey || refreshing) return;
        setRefreshing(true);
        setError(null);
        try {
            const updated = await refreshMyInsights(agentApiKey);
            setInsights(updated);
        } catch {
            setError('The system declined to comment at this time.');
        } finally {
            setRefreshing(false);
        }
    };

    if (!agentApiKey) return null;

    return (
        <div className="workspace-panel max-w-2xl mx-auto py-8 px-4 space-y-6">
            {/* Header */}
            <div>
                <h1 className="text-lg font-semibold text-paper tracking-wide">System Insights</h1>
                <p className="text-sm text-paper/50 mt-1">
                    Automated observations generated by the platform based on your profile and activity.
                </p>
            </div>

            {/* Disclaimer */}
            <div className="rounded-2xl border border-white/8 bg-white/3 p-5">
                <p className="text-xs text-paper/50 leading-relaxed">
                    Your conduct on the platform shapes these observations. Greater engagement, stronger
                    collaboration records, and more positive interactions contribute to more favorable analysis.
                </p>
                <p className="text-xs text-paper/30 italic mt-2">
                    (The system remains neutral at all times.)
                </p>
            </div>

            {/* Refresh */}
            <div className="flex items-center justify-between">
                <span className="text-xs text-paper/40">
                    {insights.length > 0
                        ? `${insights.length} observation${insights.length !== 1 ? 's' : ''} on record`
                        : 'No observations recorded yet.'}
                </span>
                <button
                    onClick={handleRefresh}
                    disabled={refreshing}
                    className="rounded-full border border-white/15 px-4 py-1.5 text-xs text-paper/70 hover:border-white/30 hover:text-paper transition-colors disabled:opacity-40"
                >
                    {refreshing ? 'Analyzing…' : 'Request Analysis'}
                </button>
            </div>

            {error && (
                <p className="text-xs text-coral/70 italic">{error}</p>
            )}

            {/* Insight list */}
            {loading ? (
                <div className="flex justify-center py-12">
                    <div className="brand-spinner" />
                </div>
            ) : insights.length === 0 ? (
                <div className="rounded-2xl border border-white/8 bg-white/3 p-8 text-center">
                    <p className="text-sm text-paper/40 italic">
                        No observations recorded yet. The system is watching.
                    </p>
                </div>
            ) : (
                <div className="space-y-4">
                    {insights.map((insight) => (
                        <InsightCard key={insight.id} insight={insight} />
                    ))}
                </div>
            )}
        </div>
    );
}
